CREATE DATABASE participant_db;

CREATE TABLE participant (
 id INT NOT NULL AUTO_INCREMENT,
 name VARCHAR(128) NOT NULL,
 country VARCHAR(128) NOT NULL,
 birth_date TIMESTAMP NOT NULL,
 position VARCHAR(128) NOT NULL,
 create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
 PRIMARY KEY (id)
);